/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.petdiary.view;

import br.com.petdiary.dao.TutorDAO;
import br.com.petdiary.model.Telefone;
import br.com.petdiary.model.Tutor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keila
 */
public class TelaListaTutores extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListaTutores.class.getName());

    private boolean modoSelecao = false;
    private Object telaOrigem;
    private List<Tutor> listaAtual = new ArrayList<>();

    /**
     * Creates new form TelaListaTutores
     */
    public TelaListaTutores() {
        initComponents();
        setLocationRelativeTo(null);
        carregarTutores();
    }

    public TelaListaTutores(Object telaOrigem) {
        initComponents();
        setLocationRelativeTo(null);
        carregarTutores();

        this.modoSelecao = true;
        this.telaOrigem = telaOrigem;

        btnNovo.setVisible(false);
        btnEditar.setVisible(false);
        btnVoltar.setText("Cancelar");
    }

    private void carregarTutores() {
        DefaultTableModel model = (DefaultTableModel) tblTutoresCadastrados.getModel();
        model.setRowCount(0);

        listaAtual.clear();

        TutorDAO dao = new TutorDAO();
        List<Tutor> listaBanco = dao.listar();        

        for (Tutor t : listaBanco) {
            String telefones = "";
            
            for (Telefone tel : t.getTelefones()) {
                if (!telefones.isEmpty()) {
                    telefones += ", ";
                }
                telefones += tel.getNumero();
            }
            listaAtual.add(t);
            model.addRow(new Object[]{
                t.getNome(),
                t.getEmail(),
                telefones
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtBuscaNomeTutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTutoresCadastrados = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnVerAnimais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Tutores");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jLabel1.setText("Tutores Cadastrados");

        jLabel2.setText("Nome do tutor:");

        jLabel3.setText("Lista de tutores:");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        txtBuscaNomeTutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaNomeTutorKeyReleased(evt);
            }
        });

        tblTutoresCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Telefones"
            }
        ));
        tblTutoresCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTutoresCadastradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTutoresCadastrados);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        btnVerAnimais.setText("Ver animais desse tutor");
        btnVerAnimais.addActionListener(this::btnVerAnimaisActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaNomeTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnVoltar)
                        .addComponent(btnVerAnimais, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaNomeTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerAnimais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar))
                .addGap(29, 29, 29)
                .addComponent(btnVoltar)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblTutoresCadastrados.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um tutor!");
            return;
        }

        Tutor tutorSelecionado = listaAtual.get(linha);

        TelaCadastroTutores tela = new TelaCadastroTutores(tutorSelecionado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (modoSelecao) {
            this.dispose();
        } else {
            TelaInicial tela = new TelaInicial();
            tela.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtBuscaNomeTutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaNomeTutorKeyReleased
        String busca = txtBuscaNomeTutor.getText().toLowerCase();

        DefaultTableModel model = (DefaultTableModel) tblTutoresCadastrados.getModel();
        model.setRowCount(0);

        listaAtual.clear();

        TutorDAO dao = new TutorDAO();
        List<Tutor> listaBanco = dao.listar();

        for (Tutor t : listaBanco) {
            String telefones = "";
            
            for (Telefone tel : t.getTelefones()) {
                if (!telefones.isEmpty()) {
                    telefones += ", ";
                }
                telefones += tel.getNumero();
            }
            if (t.getNome().toLowerCase().contains(busca)) {
                listaAtual.add(t);
                model.addRow(new Object[]{
                    t.getNome(),
                    t.getEmail(),
                    telefones
                });
            }
        }
    }//GEN-LAST:event_txtBuscaNomeTutorKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaCadastroTutores tela = new TelaCadastroTutores();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tblTutoresCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTutoresCadastradosMouseClicked
        if (modoSelecao) {
            int linha = tblTutoresCadastrados.getSelectedRow();

            if (linha == -1) {
                return;
            }

            Tutor tutorSelecionado = listaAtual.get(linha);

            if (telaOrigem instanceof TelaCadastroAnimais tela) {
                tela.receberTutorSelecionado(tutorSelecionado);
            }

            if (telaOrigem instanceof TelaAtendimentoVeterinario tela) {
                tela.receberTutorSelecionado(tutorSelecionado);
            }
            dispose();
        }
    }//GEN-LAST:event_tblTutoresCadastradosMouseClicked

    private void btnVerAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAnimaisActionPerformed
        int linha = tblTutoresCadastrados.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um tutor!");
            return;
        }

        Tutor tutorSelecionado = listaAtual.get(linha);

        TelaAnimaisDoTutor tela = new TelaAnimaisDoTutor(tutorSelecionado);
        tela.setVisible(true);
    }//GEN-LAST:event_btnVerAnimaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaListaTutores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVerAnimais;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTutoresCadastrados;
    private javax.swing.JTextField txtBuscaNomeTutor;
    // End of variables declaration//GEN-END:variables
}
